# Mykola Avramuk Jekyll Theme Config

title: Mykola Avramuk
email: avramuk89@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://avramukk.com"

# Build settings
plugins:
  - jekyll-feed

